name: C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake pkg-config libjpeg-dev libtiff-dev libpng-dev
        sudo apt-get install -y libavcodec-dev libavformat-dev libswscale-dev libv4l-dev
        sudo apt-get install -y libxvidcore-dev libx264-dev
        sudo apt-get install -y libgtk-3-dev
        sudo apt-get install -y libatlas-base-dev gfortran
        sudo apt-get install -y libopencv-dev

    - name: Build project
      run: |
        mkdir -p build
        cd build
        cmake ..
        make

    - name: Run tests
      run: |
        cd build
        ./camera_app
